import numpy as np
import math

from scripts.wiener import lms_step


def calc_attenuation(x: np.ndarray, res: np.ndarray) -> float:
    """
    Attenuation, how much quieter(dB) signal becomes after ANC compared to original loudness

    Args:
        x: reference mic signal
        res: x - residual error
    """

    P_before = np.sum(np.abs(x) ** 2)  # db
    P_after = np.sum(np.abs(res) ** 2)  # db

    return math.log10(P_before / P_after)


def lms_anc(x: np.ndarray, d: np.ndarray, taps: int, lr: float):
    """
    LMS adaptive filter reframed as feedforward ANC (no secondary path yet)

    reference mic is placed upstream of  primary path(closer to source) pikcing up noise before it propgates through
    the error mic(delay is the budget for how fast algorithm needs to work), all before d arrives
    the filter(w_n) estimate the path's effect via FIR coefs

    Args:
        x: reference mic signal
        d: noise as it arrives at the error mic (through the primary path)
        taps: number of filter coefficients (FIR filter order)
        lr: learning rate / step size

    Returns:
        x, d: inputs, sliced to align with y/e (first `taps` samples dropped,
              since the loop needs a full window before it can start)
        y: anti-noise generated by the adaptive filter at each step
        e: residual noise, d - y, what ANC is trying to drive to zero
        w_history: filter coefficients w_n after each step (len n-taps+1, includes initial zeros)
    """
    assert len(x) == len(d)

    n = len(x)
    w_n = np.zeros(taps)

    y = np.empty(n - taps)
    e = np.empty(n - taps)
    w_history = [w_n.copy()]

    for i in range(taps, n):
        x_window = x[i - taps : i][::-1]
        y_hat = w_n @ x_window
        error = d[i] - y_hat

        y[i - taps] = y_hat
        e[i - taps] = error

        w_n = lms_step(x_window, error, w_n, lr)
        w_history.append(w_n.copy())

    return x[taps:], d[taps:], y, e, w_history
