import numpy as np
import math

from scripts.wiener import lms_step
from scripts.gen_noise import FIR_filter


def calc_attenuation(x: np.ndarray, res: np.ndarray) -> float:
    """
    Attenuation, how much quieter(dB) signal becomes after ANC compared to original loudness

    Args:
        x: reference mic signal
        res: x - residual error
    """

    P_before = np.sum(np.abs(x) ** 2)  # db
    P_after = np.sum(np.abs(res) ** 2)  # db

    return math.log10(P_before / P_after)


def lms_anc(x: np.ndarray, d: np.ndarray, taps: int, lr: float, s_taps: np.ndarray = None, s_hat_taps: np.ndarray = None, normalize: bool = False):

    """
    FxLMS adaptive filter reframed as feedforward ANC

    reference mic is placed upstream of  primary path(closer to source) pikcing up noise before it propgates through
    the error mic(delay is the budget for how fast algorithm needs to work), all before d arrives
    the filter(w_n) estimate the path's effect via FIR coefs

                        Primary path P(z)
    Noise source x[n] --------------------------> d[n] ----+
                                                           |
                                                           v
                                                       Error mic
                                                           |
                                                           v
                                                         e[n]
                                                           ^
                                                           |
    Reference x[n] -> Adaptive filter W(z) -> y[n] -> S(z)-+
                                                   Secondary path
    Adaptive filter takes in x[n] creates after it propgates through the air and other mediums (d[n]) and creates y[n]
    y[n] still needs to propgate to the speaker to cancel out

    Args:
        x: reference mic signal
        d: noise as it arrives at the error mic (through the primary path)
        taps: number of filter coefficients for main path
        lr: learning rate / step size
        s_taps: secondary path (speaker -> error mic), fixed, applied to y[n]
                to produce what actually arrives at the error mic. Never
                updated by gradient descent. Defaults to an identity path
                ([1.0], i.e. no secondary path), which reduces this to plain
                LMS -- pass real taps to actually exercise FxLMS.
        s_hat_taps: filter's estimate of the secondary path, used to filter
                    the reference x[n] before correlating it with error[n]
                    (the "Filtered-X" step -- corrects the gradient direction
                    that the raw secondary path distorts). Defaults to a
                    perfect estimate (s_hat_taps = s_taps) if not given.
        normalize: NLMS mode -- scale lr per-step by 1/(power of the current
                   filtered-reference window), instead of using a fixed step
                   size (LMS)

    Returns:
        x, d: inputs, sliced to align with y/e (first `taps` samples dropped,
              since the loop needs a full window before it can start)
        y: anti-noise generated by the adaptive filter at each step
        e: residual noise, d - y_sec, what ANC is trying to drive to zero
        w_history: filter coefficients w_n after each step (len n-taps+1, includes initial zeros)
    """
    assert len(x) == len(d)
    epsil = 0.00001 # idk to paramtize ngl

    if s_taps is None:
        s_taps = np.array([1.0])
    if s_hat_taps is None:
        s_hat_taps = s_taps

    n = len(x)
    w_n = np.zeros(taps)

    # filtered reference x_filt[n] = (Shat(z) * x)[n], used for the gradient only
    x_filt = FIR_filter(x, s_hat_taps)

    y = np.empty(n - taps)
    e = np.empty(n - taps)
    w_history = [w_n.copy()]

    y_buf = np.zeros(len(s_taps))  # history of past y_hat, for the real secondary path

    for i in range(taps, n):
        x_window = x[i - taps : i][::-1]
        y_hat = w_n @ x_window

        y_buf = np.roll(y_buf, 1)
        y_buf[0] = y_hat
        y_sec = s_taps @ y_buf  # y_hat as it actually arrives at the error mic, through S(z)

        error = d[i] - y_sec

        y[i - taps] = y_hat
        e[i - taps] = error

        x_filt_window = x_filt[i - taps : i][::-1]

        step_lr = lr
        if normalize:
            x_filt_power = np.mean(x_filt_window ** 2)
            step_lr = lr / (x_filt_power + epsil)
        
        # update step in grad descent
        w_n = lms_step(x_filt_window, error, w_n, step_lr)
        w_history.append(w_n.copy())

    return x[taps:], d[taps:], y, e, w_history
