import numpy as np

from scripts.wiener import lms_step

def lms_anc(x:np.ndarray, d:np.ndarray, taps:int, lr:float):
    """
    LMS adaptive filter reframed as feedforward ANC (no secondary path yet)

    reference mic is placed upstream of  primary path(closer to source) pikcing up noise before it propgates through
    the error mic(delay is the budget for how fast algorithm needs to work), all before d arrives
    the filter(w_n) estimate the path's effect via FIR coefs

    Args:
        x: reference mic signal
        d: noise as it arrives at the error mic (through the primary path)
        taps: number of filter coefficients (FIR filter order)
        lr: learning rate / step size

    Returns:
        x, d: inputs, sliced to align with y/e (first `taps` samples dropped,
              since the loop needs a full window before it can start)
        y: anti-noise generated by the adaptive filter at each step
        e: residual noise, d - y, what ANC is trying to drive to zero
    """
    assert(len(x) == len(d))

    n = len(x)
    w_n = np.zeros(taps)

    y = np.empty(n - taps)
    e = np.empty(n - taps)

    for i in range(taps, n):
        x_window = x[i-taps:i][::-1]
        y_hat = w_n @ x_window
        error = d[i] - y_hat

        y[i-taps] = y_hat
        e[i-taps] = error

        w_n = lms_step(x_window, error, w_n, lr)

    return x[taps:], d[taps:], y, e





