// error_block testbench -- NLMS energy + divide + weight update.
//
// The DUT does not contain its own memories: it reads w[tap_idx] and
// x_f[tap_idx] and emits w_new_tap/w_wr_en. This TB models those two memories
// (xf_model reads only; w_model loaded with the test vector) and captures every
// w_new_tap written back into got_wnew, which is then compared bit-exact
// against golden vectors generated by chip/dv/gen_vectors.py.

module error_block_tb;

  import globals::*;
  import dv_globals::*;

  `include "error_block_vectors.svh"

  localparam time CLK_PERIOD = 20ns;
  localparam int  TAP_CNT_W  = $clog2(TAP_LEN);

  logic clk;
  logic rst_n;

  logic e_n_valid;
  sample_t e_n;
  logic [TAP_CNT_W-1:0] tap_idx;
  sample_t w_n_tap;
  xf_t x_fn_tap;
  sample_t w_new_tap;
  logic w_wr_en;
  logic w_n_updated;
  logic mu_saturated;

  error_block dut (
      .clk         (clk),
      .rst_n       (rst_n),
      .e_n_valid   (e_n_valid),
      .e_n         (e_n),
      .tap_idx     (tap_idx),
      .w_n_tap     (w_n_tap),
      .x_fn_tap    (x_fn_tap),
      .w_new_tap   (w_new_tap),
      .w_wr_en     (w_wr_en),
      .w_n_updated (w_n_updated),
      .mu_saturated(mu_saturated)
  );

  // ---- TB-side memory models ----
  sample_t w_model [TAP_LEN];  // loaded once per case, read via .w_n_tap
  sample_t xf_model[TAP_LEN];  // read via .x_fn_tap
  sample_t got_wnew[TAP_LEN];  // captured write-backs, checked vs golden

  always_comb begin
    w_n_tap  = w_model[tap_idx];
    x_fn_tap = xf_t'(xf_model[tap_idx]);
  end

  always_ff @(posedge clk) begin
    if (w_wr_en) got_wnew[tap_idx] <= w_new_tap;
  end

  initial begin
    clk = 1'b0;
    forever #(CLK_PERIOD / 2) clk = ~clk;
  end

  initial begin
    $dumpfile({DV_OUT_DIR, "error_block_tb.vcd"});
    $dumpvars(0, error_block_tb);
  end

  task automatic reset_dut();
    rst_n = 1'b0;
    e_n_valid = 1'b0;
    e_n = '0;
    repeat (4) @(posedge clk);
    rst_n = 1'b1;
    repeat (2) @(posedge clk);
  endtask

  // run one case end to end
  task automatic run_case(input sample_t xf_vec[TAP_LEN], input sample_t w_vec[TAP_LEN],
                          input sample_t e_val, input int mu_sat_val,
                          input sample_t wnew_vec[TAP_LEN], input string lbl);
    int i;
    for (i = 0; i < TAP_LEN; i++) begin
      xf_model[i] = xf_vec[i];
      w_model[i]  = w_vec[i];
    end

    // one-cycle e_n_valid pulse, e_n held stable across the capturing edge
    @(negedge clk);
    e_n       = e_val;
    e_n_valid = 1'b1;
    @(posedge clk);
    @(negedge clk);
    e_n_valid = 1'b0;

    // poll for completion
    for (i = 0; i < 1000; i++) begin
      @(posedge clk);
      if (w_n_updated) break;
    end
    if (i == 1000) $fatal(1, "[%0s] w_n_updated never asserted", lbl);

    // check every written weight bit-exactly
    for (i = 0; i < TAP_LEN; i++) begin
      if (got_wnew[i] !== wnew_vec[i])
        $fatal(1, "[%0s] w[%0d] = %h, expected %h", lbl, i, got_wnew[i], wnew_vec[i]);
    end
    if (mu_saturated !== (mu_sat_val != 0))
      $fatal(1, "[%0s] mu_saturated = %0d, expected %0d", lbl, mu_saturated, mu_sat_val);

    $display("[%0s] pass: 32 taps match golden, mu_saturated=%0d", lbl, mu_saturated);
  endtask

  initial begin
    reset_dut();
    run_case(EB_XF_A, EB_W_A, EB_E_A, EB_MU_SAT_A, EB_WNEW_A, "A");

    reset_dut();
    run_case(EB_XF_B, EB_W_B, EB_E_B, EB_MU_SAT_B, EB_WNEW_B, "B");
    run_case(EB_XF_C, EB_W_C, EB_E_C, EB_MU_SAT_C, EB_WNEW_C, "C");
    run_case(EB_XF_D, EB_W_D, EB_E_D, EB_MU_SAT_D, EB_WNEW_D, "D");

    // robustness: a second e_n_valid while the FSM is busy must be ignored
    begin
      int i;
      reset_dut();
      for (i = 0; i < TAP_LEN; i++) begin
        xf_model[i] = EB_XF_B[i];
        w_model[i]  = EB_W_B[i];
      end
      @(negedge clk);
      e_n       = EB_E_B;
      e_n_valid = 1'b1;
      @(posedge clk);
      @(negedge clk);
      e_n_valid = 1'b0;
      // spurious pulse 10 cycles into the pass
      repeat (10) @(posedge clk);
      @(negedge clk);
      e_n       = 16'sh7FFF;  // different e, must be ignored
      e_n_valid = 1'b1;
      @(posedge clk);
      @(negedge clk);
      e_n_valid = 1'b0;

      // poll for the (single) completion
      for (i = 0; i < 1000; i++) begin
        @(posedge clk);
        if (w_n_updated) break;
      end
      if (i == 1000) $fatal(1, "robustness: w_n_updated never asserted");
      // no second pass may follow: the spurious pulse was ignored
      for (i = 0; i < 200; i++) begin
        @(posedge clk);
        if (w_n_updated) $fatal(1, "robustness: spurious e_n_valid started a second pass");
      end
      for (i = 0; i < TAP_LEN; i++)
      if (got_wnew[i] !== EB_WNEW_B[i])
        $fatal(1, "robustness: w[%0d] corrupted = %h, expected %h", i, got_wnew[i], EB_WNEW_B[i]);
      $display("robustness pass: spurious e_n_valid mid-pass ignored");
    end

    $display("T=%0t: error_block_tb done.", $time);
    $finish;
  end

  initial begin
    #100ms $fatal(1, "timeout");
  end

endmodule
