"""
Generate golden reference vectors for the RTL testbenches.

Runs the fixed-point golden model (chip/dv/golden) over deterministic inputs
and writes .svh include files with the exact raw-integer values the RTL must
reproduce. Regenerate with:

    PYTHONPATH=.:chip/dv .venv/bin/python chip/dv/gen_vectors.py

The generated files are committed, so run_tb.sh needs no Python at TB time.
"""
import os

import numpy as np

from golden import fmt as F, mac as M, fir as FIR, update as U

HERE = os.path.dirname(os.path.abspath(__file__))

fmt = F.DEFAULT
TAP_LEN = 32


def q_raw(x, q):
    """Round float x into Q and return its stored integer."""
    return int(np.round(x * (1 << q.frac_bits)))


def emit_sv(path, decls):
    lines = ["// generated by chip/dv/gen_vectors.py -- do not edit", ""]
    for decl in decls:
        lines.append(decl + ";")
        lines.append("")
    with open(path, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {path}")


def arr(name, typ, values):
    body = ", ".join(str(v) for v in values)
    return f"localparam {typ} {name} [{len(values)}] = '{{{body}}}"


def fmt_signed(v, bits):
    return v


# ---------------------------------------------------------------------------
# error_block vectors
# ---------------------------------------------------------------------------

def error_block_case(rng, label, xf_scale, w_scale, e_val):
    xf_raw = [q_raw(v, fmt.xf) for v in rng.uniform(-xf_scale, xf_scale, TAP_LEN)]
    w_raw = [q_raw(v, fmt.coef) for v in rng.uniform(-w_scale, w_scale, TAP_LEN)]
    e_raw = q_raw(e_val, fmt.sample)

    xf = [F.from_raw(v, fmt.xf, fmt) for v in xf_raw]
    w = [F.from_raw(v, fmt.coef, fmt) for v in w_raw]
    e = F.from_raw(e_raw, fmt.sample, fmt)

    eres = U.energy(xf, fmt)
    st = U.step_size(eres.acc, 0.1, 0.00001, fmt)
    w_new, recs = U.update_taps(w, xf, e, st.mu, fmt)

    mu_raw = F.raw(st.mu)
    w_new_raw = [F.raw(x) for x in w_new]
    return {
        "label": label,
        "xf": xf_raw, "w": w_raw, "e": e_raw,
        "mu": mu_raw, "mu_sat": 1 if st.saturated else 0,
        "w_new": w_new_raw,
    }


def gen_error_block():
    blocks = []
    cases = []
    # Case A: realistic mid-level signals, no saturation.
    cases.append(error_block_case(np.random.default_rng(1234), "A", 0.8, 0.4, 0.05))
    # Case B: large signals to exercise rounding + weight railing.
    cases.append(error_block_case(np.random.default_rng(5678), "B", 1.5, 0.99, 0.4))
    # Case C: quiet reference -> large mu (still no step saturation at lr=0.1).
    cases.append(error_block_case(np.random.default_rng(9012), "C", 0.02, 0.4, 0.001))

    # Case D: crafted to rail the coefficient register both directions.
    # Quiet reference (tiny x_f -> E near eps -> mu large), max e, alternating
    # x_f sign so even taps clamp to +32767 and odd taps clamp to -32768.
    xf_d = [9 if k % 2 == 0 else -9 for k in range(TAP_LEN)]
    w_d = [0] * TAP_LEN
    e_d = 32767
    xf = [F.from_raw(v, fmt.xf, fmt) for v in xf_d]
    w = [F.from_raw(v, fmt.coef, fmt) for v in w_d]
    e = F.from_raw(e_d, fmt.sample, fmt)
    eres = U.energy(xf, fmt)
    st = U.step_size(eres.acc, 0.1, 0.00001, fmt)
    w_new, _ = U.update_taps(w, xf, e, st.mu, fmt)
    cases.append({"label": "D", "xf": xf_d, "w": w_d, "e": e_d,
                  "mu": F.raw(st.mu), "mu_sat": 1 if st.saturated else 0,
                  "w_new": [F.raw(x) for x in w_new]})

    blocks.append(f"localparam int EB_N_CASES = {len(cases)}")
    for c in cases:
        l = c["label"]
        blocks.append(arr(f"EB_XF_{l}", "logic signed [15:0]", c["xf"]))
        blocks.append(arr(f"EB_W_{l}", "logic signed [15:0]", c["w"]))
        blocks.append(f"localparam logic signed [15:0] EB_E_{l} = {c['e']}")
        blocks.append(f"localparam logic signed [31:0] EB_MU_{l} = {c['mu']}")
        blocks.append(f"localparam int EB_MU_SAT_{l} = {c['mu_sat']}")
        blocks.append(arr(f"EB_WNEW_{l}", "logic signed [15:0]", c["w_new"]))

    emit_svg = emit_sv
    emit_svg(os.path.join(HERE, "error_block_vectors.svh"), blocks)


# ---------------------------------------------------------------------------
# s_hat_fir vectors
# ---------------------------------------------------------------------------

def gen_s_hat_fir():
    rng = np.random.default_rng(4242)
    s_hat_raw = [q_raw(v, fmt.coef) for v in rng.uniform(-0.5, 0.5, TAP_LEN)]
    M = 40
    x_seq_raw = [q_raw(v, fmt.sample) for v in rng.uniform(-0.8, 0.8, M)]

    # golden reference: push each x, compute x_f[n] with zero-padded history
    xf_seq = []
    x_line = [F.from_raw(0, fmt.sample, fmt)] * TAP_LEN
    s_hat = [F.from_raw(v, fmt.coef, fmt) for v in s_hat_raw]
    for xr in x_seq_raw:
        x = F.from_raw(xr, fmt.sample, fmt)
        x_line = [x] + x_line[:-1]
        xf = FIR.filter_shat(s_hat, x_line, fmt)
        xf_seq.append(F.raw(xf.out))

    blocks = [
        arr("SH_S", "logic signed [15:0]", s_hat_raw),
        arr("SH_X", "logic signed [15:0]", x_seq_raw),
        arr("SH_XF", "logic signed [15:0]", xf_seq),
        f"localparam int SH_M = {M}",
    ]
    emit_sv(os.path.join(HERE, "s_hat_fir_vectors.svh"), blocks)


if __name__ == "__main__":
    gen_error_block()
    gen_s_hat_fir()
