"""
Generate full-system ("anc") test vectors: x/e stimulus and golden reference
outputs for anchor_top integration.

Pipeline (mirrors golden/demo.check_against_ans, but golden at DEFAULT):

  1. lms_anc (scripts/ans.py) runs the *plant* in float64 and produces the
     residual e[n] the chip would see at the error mic (the real secondary path
     S(z) is applied there, so no plant is needed in RTL).
  2. golden.core (chip/dv/golden) re-derives the anti-noise y[n] and weight
     trajectory from that same (x, e) input stream, in the DEFAULT fixed-point
     formats the RTL implements. This is the bit-exact reference.

The chip's adc/err ports are 12-bit offset-binary, so x and e are generated as
12-bit codes and mapped to Q1.15 exactly the way sample_in/anchor_top do
(invert MSB, zero-pad low 4 bits). golden is driven with those exact Q1.15
values via F.from_raw.

Writes (into chip/dv/):
  anc_x.mem     x codes (PRIME + ANC_N), 12-bit hex
  anc_e.mem     e codes (ANC_N), 12-bit hex
  anc_y.mem     expected y accumulator (ANC_N), 64-bit two's-complement hex
  anc_w.mem     expected final w[] (TAP_LEN), 16-bit hex
  anc_shat.mem  s_hat[] to load (TAP_LEN), 16-bit hex
  anc_params.svh  ANC_N / PRIME constants

Regenerate:  ANC_N=8192 PYTHONPATH=.:chip/dv .venv/bin/python chip/dv/gen_anc_vectors.py
"""

import os

import numpy as np

from golden import fmt as F
from golden import core as C

HERE = os.path.dirname(os.path.abspath(__file__))

LR, EPS = 0.1, 0.00001
TAPS = 32


def code_to_q15(code: int) -> int:
    """12-bit offset-binary code -> Q1.15 signed 16-bit raw (mirrors sample_in)."""
    msb = (code >> 11) & 1
    sign = 0 if msb else 1
    raw = (sign << 15) | ((code & 0x7FF) << 4)
    return raw - (1 << 16) if raw & 0x8000 else raw


def float_to_code(v: float) -> int:
    """float -> 12-bit offset-binary code (Q1.11, round + saturate)."""
    v = max(-1.0, min(v, 1.0 - 2 ** -11))
    q11 = int(round(v * 2048.0))
    q11 = max(-2048, min(q11, 2047))
    return (q11 + 2048) & 0xFFF


def q15_to_hex(raw: int, bits: int) -> str:
    return f"{raw & ((1 << bits) - 1):0{bits // 4}X}"


def gen(anc_n: int) -> None:
    total = TAPS + anc_n

    # ---- stimulus + plant ----
    # reference: a couple of tonal components (classic ANC demo), quantized to
    # the 12-bit adc. Tonal reference lets a short W(s) cancel almost
    # completely, so the ANC result is visible in the waveform.
    n_idx = np.arange(total)
    x_float = (0.3 * np.sin(2 * np.pi * 300 * n_idx / 16000.0)
               + 0.2 * np.sin(2 * np.pi * 700 * n_idx / 16000.0))
    x_code = np.array([float_to_code(v) for v in x_float], dtype=np.int64)
    xq = np.array([code_to_q15(int(c)) / 32768.0 for c in x_code])  # chip's x

    # primary path: reference noise -> noise at the error mic
    p_taps = 0.6 * 0.7 ** np.arange(6)
    d = np.convolve(xq, p_taps)[:total]

    # secondary path (speaker -> error mic): decaying impulse response; the
    # chip is given a perfect estimate. L1 ~= 1.6, so |x_f| <= 1.6 * 0.5 < 2.
    s_taps = 0.4 * 0.75 ** np.arange(TAPS)
    s_hat = s_taps.copy()

    from scripts.ans import lms_anc
    _, _, _, e_float, _ = lms_anc(
        xq, d, TAPS, LR,
        s_taps=s_taps, s_hat_taps=s_hat,
        normalize=True, keep_history=False)

    e_code = np.array([float_to_code(float(v)) for v in e_float], dtype=np.int64)

    # ---- golden fixed-point reference ----
    fmt = F.DEFAULT
    s_hat_q15 = [int(np.clip(round(v * 32768.0), -32768, 32767)) for v in s_hat]
    x_q15 = [code_to_q15(int(c)) for c in x_code]
    e_q15 = [code_to_q15(int(c)) for c in e_code]

    s_hat_fxp = [F.from_raw(v, fmt.coef, fmt) for v in s_hat_q15]
    x_fxp = [F.from_raw(v, fmt.sample, fmt) for v in x_q15]
    e_fxp = [F.from_raw(v, fmt.sample, fmt) for v in e_q15]

    st = C.ChipState.init(s_hat_fxp, TAPS, LR, EPS, fmt, w=[0.0] * TAPS)
    st = C.prime(st, x_fxp[:TAPS])

    y_acc = []
    step = max(1, anc_n // 10)
    for j in range(anc_n):
        t = C.sample_step(st, x_fxp[TAPS + j], e_fxp[j])
        y_acc.append(F.raw(t.y.seq.acc))
        st = t.state_out
        if anc_n >= 100 and j % step == 0:
            print(f"  golden {j}/{anc_n}")
    w_final = [F.raw(v) for v in st.w]

    # ---- emit ----
    def wmem(name, values, bits):
        with open(os.path.join(HERE, name), "w") as f:
            f.write("\n".join(q15_to_hex(v, bits) for v in values) + "\n")
        print(f"wrote {os.path.join(HERE, name)} ({len(values)} entries)")

    wmem("anc_x.mem", x_code.tolist(), 12)
    wmem("anc_e.mem", e_code.tolist(), 12)
    wmem("anc_y.mem", y_acc, 64)
    wmem("anc_w.mem", w_final, 16)
    wmem("anc_shat.mem", s_hat_q15, 16)

    with open(os.path.join(HERE, "anc_params.svh"), "w") as f:
        f.write("// generated by chip/dv/gen_anc_vectors.py -- do not edit\n")
        f.write(f"localparam int ANC_N    = {anc_n};\n")
        f.write(f"localparam int ANC_PRIME = {TAPS};\n")
    print(f"wrote {os.path.join(HERE, 'anc_params.svh')}")


if __name__ == "__main__":
    n = int(os.environ.get("ANC_N", "8192"))
    gen(n)